Update aria2c

diff --git a/aria2c b/aria2c
--- a/aria2c
+++ b/aria2c
@@ -9,7 +9,7 @@
 # Description:       Enable aria2c by daemon.
 ### END INIT INFO
 DAEMON=/usr/local/bin/aria2c
-CONFPATH=/etc/aria2/aria2c.conf
+ROOTARIA=/etc/aria2
 WORKPATH=/usr/share/nginx/www
 
 [ -f "$DAEMON" ] || {
@@ -17,8 +17,11 @@ DAEMON=`which aria2c`
 [ -z "$DAEMON" ] && echo "Not found aria2c! " && exit 1
 }
 
+DAEMONPID=`ps -e |grep aria2c |awk '{ print $1 }'`
+
 case "$1" in
 start)
+[ ! -z "$DAEMONPID" ] && echo "aria2c already in run [$DAEMONPID]." && exit 0
 mkdir -p /root/.aria2
 mkdir -p $WORKPATH/restore
 mkdir -p $WORKPATH/torrent
@@ -26,6 +29,9 @@ mkdir -p $WORKPATH/download
 cp -uf $WORKPATH/download/*.torrent $WORKPATH/torrent >/dev/null 2>&1
 rm -rf $WORKPATH/download/* >/dev/null 2>&1
 ln -sf $WORKPATH/restore/* $WORKPATH/download >/dev/null 2>&1
+ln -sf $WORKPATH/download /root >/dev/null 2>&1
+ln -sf $ROOTARIA/Index/theme $WORKPATH
+ln -sf $ROOTARIA/Index/favicon.ico $WORKPATH
 iptables -A INPUT -p tcp --dport 6800 -j ACCEPT
 iptables -A INPUT -p tcp --dport 6881:6999 -j ACCEPT
 iptables -A INPUT -p udp --dport 6881:6999 -j ACCEPT
@@ -33,14 +39,23 @@ iptables -A OUTPUT -p tcp --dport 6800 -j ACCEPT
 iptables -A OUTPUT -p tcp --dport 6881:6999 -j ACCEPT
 iptables -A OUTPUT -p udp --dport 6881:6999 -j ACCEPT
 sleep 1
-$DAEMON --conf-path=$CONFPATH -D
-echo "aria2c Success! "
+$DAEMON --conf-path=$ROOTARIA/aria2c.conf -D
+DAEMONPID=`ps -e |grep aria2c |awk '{ print $1 }'`
+[ ! -z "$DAEMONPID" ] && echo "aria2c START Success [$DAEMONPID]! "
+[ -z "$DAEMONPID" ] && echo "aria2c START Fail! "
 ;;
 stop)
-printf "aria2c " && killall -9 aria2c >/dev/null 2>&1
+[ -z $DAEMONPID ] && echo "aria2c not work ." && exit 1
+killall -q -9 aria2c >/dev/null 2>&1
+[ -z $DAEMONPID ] && echo "aria2c STOP Success."
+[ ! -z $DAEMONPID ] && echo "aria2c STOP Fail."
+;;
+restart)
+killall -q -9 aria2c >/dev/null 2>&1
+$0 start;
 ;;
 *)
-echo "Usage: aria2c {start|stop}"
+echo "Usage: aria2c {start|stop|restart}"
 exit 1
 esac
 exit 0
